# MQTT
mp.messaging.incoming.nili3-co2.connector=smallrye-mqtt
mp.messaging.incoming.nili3-co2.host=${MQTT_HOST}
mp.messaging.incoming.nili3-co2.port=${MQTT_PORT}
mp.messaging.incoming.nili3-co2.username=${MQTT_USERNAME:}
mp.messaging.incoming.nili3-co2.password=${MQTT_PASSWORD:}
mp.messaging.incoming.nili3-co2.topic=nili3/sensor/nili3_co2/state

mp.messaging.incoming.nili3-temperature.connector=smallrye-mqtt
mp.messaging.incoming.nili3-temperature.host=${MQTT_HOST}
mp.messaging.incoming.nili3-temperature.port=${MQTT_PORT}
mp.messaging.incoming.nili3-temperature.username=${MQTT_USERNAME:}
mp.messaging.incoming.nili3-temperature.password=${MQTT_PASSWORD:}
mp.messaging.incoming.nili3-temperature.topic=nili3/sensor/nili3_temperature/state

# Datasource
quarkus.datasource.db-kind=postgresql
quarkus.datasource.devservices.enabled=true
quarkus.datasource.devservices.db-name=db
quarkus.datasource.devservices.username=app
quarkus.datasource.devservices.password=app

# Flyway
quarkus.flyway.migrate-at-start=true

# Hibernate
%dev.quarkus.hibernate-orm.schema-management.strategy=drop-and-create
%prod.quarkus.hibernate-orm.schema-management.strategy=none
